on:
  push:
    branches:
      - develop

name: Deploy Decagon Website

jobs:
  staging:
    name: Deploy to staging
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: https://staging-institute.decagoninstitute.com/

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build Project
        run: yarn build
        env:
          REACT_APP_PROD_BASE_URL: ${{ secrets.WEB_API_URL }}
          REACT_APP_MAIL_FROM: ${{ secrets.WEB_MAIL_FROM }}
          REACT_APP_MAIL_HOST: ${{ secrets.WEB_MAIL_HOST }}

      - name: Deployment
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: './build'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  prod:
    name: Deploy to Production
    runs-on: ubuntu-latest

    needs: staging

    environment:
      name: production
      url: https://decagon.institute

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build Project
        run: yarn build
        env:
          REACT_APP_PROD_BASE_URL: ${{ secrets.WEB_API_URL }}
          REACT_APP_MAIL_FROM: ${{ secrets.WEB_MAIL_FROM }}
          REACT_APP_MAIL_HOST: ${{ secrets.WEB_MAIL_HOST }}

      - name: Deployment
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: './build'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
